Vagrant.configure("2") do |config|
  config.vm.base_mac = "08002700E9DF"

  # Disable the base shared folder, guest additions are unavailable.
 #config.vm.synced_folder ".", "/vagrant", disabled: true
end
